### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by playahata** [IBMDecisionOptimization/docplex-examples#1]
This is telling me to set url and key in cplex_config.py and docloud_config.py  but these files do not exist.

**Comment by vberaudi** [comment]
can you please be more specific on what you did? what environment?...?

**Comment by vlkong** [comment]
@playahata This documentation section explains how to create a cplex_config.py or docloud_config.py file and where to put them:

http://ibmdecisionoptimization.github.io/docplex-doc/getting_started.html#using-the-ibm-decision-optimization-on-cloud-service

Does this answer your question ?

**Comment by vlkong** [comment]
I'm closing this issue as we don't have news since last comment.
