### ISSUE TITLE
cplex limits exceed problem

### ISSUE THREAD

**Issue by vlkong** [IBMDecisionOptimization/docplex-examples#10]
I've the same problem but I'm on a Mac. I tried installing the community edition using pip install cplex. But also registered with IBM using my student email id and downloaded the app. But I could only download it as the desktop version. I'm trying to run it from command line

_Originally posted by @Rakshith-Manandi in https://github.com/IBMDecisionOptimization/docplex-examples/issues/6#issuecomment-497567213_

**Comment by vlkong** [comment]
https://github.com/IBMDecisionOptimization/docplex-examples/issues/6#issuecomment-497643945

**Comment by vlkong** [comment]
@Rakshith-Manandi What version are you trying to run ?

**Comment by arani-mohammad** [comment]
Hi @vlkong 
I have the same problem, I was wondering if you could guide me how I can install the academic version of CPLEX on Jupiter notebook.
Is there a kind of step by step tutorial?
I know that by using pip I did install the community version and now I cannot get rid of it. (don't know how)
Thank you in advance for your time.
M

**Comment by arani-mohammad** [comment]
[https://github.com/IBMDecisionOptimization/docplex-examples/issues/6](url)

**Comment by vlkong** [comment]
@arani-mohammad please open a new issue, so that we can keep track of the resolution for your problem. Thanks.
