### ISSUE TITLE
DOcplexLimitsExceeded: **** Promotional version. Problem size limits exceeded, CPLEX code=1016

### ISSUE THREAD

**Issue by arani-mohammad** [IBMDecisionOptimization/docplex-examples#11]
Hi @vlkong,
First, thank you for dedicating your time to resolve the problems.
I have encountered the following issue while I was trying to solve a fairly medium MILP problem. 
DOcplexLimitsExceeded: **** Promotional version. Problem size limits exceeded, CPLEX code=1016
I have noticed that the version of cplex I am using on Jupiter notebook is the community edition that I installed by using pip install cplex (https://pypi.org/project/cplex/). 
I was wondering if you could possibly help me to install the academic version which is unlimited for academic purposes (since I am eligible to use it as a grad student). 
Thank you once again. 
Regards,
M. A.

**Comment by vlkong** [comment]
Hi there. Thanks for creating that issue.
As far as I know, at the moment you need to contact IBM representatives for a license.
Please contact xavier.nodet@fr.ibm.com (he is the program manager for CPLEX). To save time, please provide him the platform you wish to download.

**Comment by arani-mohammad** [comment]
Thank you very much for your help, @vlkong.

**Comment by arani-mohammad** [comment]
As @vlkong suggested, I have contacted Xavier. He provided me the latest CPLEX studio software. 
And the following is a part of his email to help if anyone has the latest CPLEX studio but does not know how to install it: 


**[As a precaution, you may want to remove the Community Edition from your Python environment, so that you don't run the risk of mixing both]
 
Once you have the software installed, you should run the
   [install-dir]/python/setup.py
script from your Python environment of choice.
This will install the correct libraries to replace the Community Edition.**


Since the problem seems solved, I close this issue.
Many thanks to @vlkong, Xavier, and the IBM company.

**Comment by louis925** [comment]
I have done the similar thing to run the `setup.py` script but didn't remove the Community Edition (installed through pip) first. Now, when I tried to remove the community version through `pip uninstall cplex`, it gave me error
```
ERROR: Cannot uninstall 'cplex'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
I didn't know the `setup.py` can mess up my `pip` environment setting...

**Comment by nodet** [comment]
Teachers, researchers and students looking for the academic version of our engines will find the information they need at http://ibm.biz/Bdzvqw. There, we explain how to register in the Academic Initiative program, from where the latest version of CPLEX Optimization Studio can be downloaded.

**Comment by HengChheang** [comment]
Hello @arani-mohammad. So I also just encountered the same problem in your previous question about the model limitations using the community edition. But as following your description, I have installed the latest version with the academic Initiative edition, however, I find it hard to find the and Cplex and setup.ly file as you mentioned in the comment section. Could you please provide a new and clear step for installing and using this edition, please? any help would be appreciated. Thank you.

**Comment by vlkong** [comment]
@HengChheang can you please open a new ticket describing your environment and problem ?
