### ISSUE TITLE
pip install cplex

### ISSUE THREAD

**Issue by arani-mohammad** [IBMDecisionOptimization/docplex-examples#13]
Hi @vlkong ,
First I am sorry because of addressing you all the time.
In the community version just by installing docplex, it seems I am not able to solve any OR problem. 
`DOcplexException: CPLEX runtime not found: please install CPLEX or solve this model on DOcplexcloud`
and the above error guides me to install cplex itself other than docplex:
`pip install cplex`
the reason for this issue is that (pip install cplex) is not working.
Since the latest version of CPLEX studio I have is 12.9, do you recommend me to install wheel version of cplex 12.8 ?[https://files.pythonhosted.org/packages/d2/c5/1d3f7c448b543e52ca2f7eac902d3618ce51bbe487171d641b4a2f984d65/cplex-12.8.0.1-cp27-cp27m-win_amd64.whl](url)
I was wondering if you could help me to solve this issue.
Many thanks

**Comment by arani-mohammad** [comment]
Hi @vlkong ,
I have noticed the only way to install cplex is to use python 3.6. 
If I change the version to 3.6 the I can easily use pip install cplex.

**Comment by vlkong** [comment]
cplex 12.8 CE does not support 3.7 and 12.9 CE is not yet on pypi. I'll make sure it gets published shortly.
Thanks
