### ISSUE TITLE
docplex.cp.model vs docplex.mp.model

### ISSUE THREAD

**Issue by arani-mohammad** [IBMDecisionOptimization/docplex-examples#17]
Hi, 
Probably my question is rudimentary, but I was wondering if anyone could just **share some informative links**. Hopefully, anyone like me can have a better understanding of the differences between docplex._cp_.model and docplex._mp_.model. 
Many thanks.

**Comment by vlkong** [comment]
Hi,

The [docpex-doc](https://github.com/IBMDecisionOptimization/docplex-doc) project contains the official documentation for docplex.

docplex.cp is the package for constraint programming.
docplex.mp is the package for mathematical programming.

This [page ](http://ibmdecisionoptimization.github.io/docplex-doc/mp_vs_cp.html) describes shortly the difference between the two of them .

From this [page](http://ibmdecisionoptimization.github.io/docplex-doc/) you can navigate to reference manuals for each package.

Thanks

**Comment by arani-mohammad** [comment]
Invaluably and extremely useful, thank you very much.
