### ISSUE TITLE
 No module named 'docplex' in Mac - Anaconda (

### ISSUE THREAD

**Issue by Shahrooz11** [IBMDecisionOptimization/docplex-examples#18]
Hi @vlkong , 

I installed anaconda 1.9.7, the python version is 3.7.3. Then used conda install -c ibmdecisionoptimization cplex . and pip insall cplex. 

However, I face this error: 
 No module named 'docplex'.

Please help. There is nothing on the net for solving this error of integrating cplex and anaconda python for Mac and Anaconda. 

Regards,
Shahrooz

**Comment by vlkong** [comment]
Hi,

Please install docplex.

conda install -c ibmdecisionoptimization docplex 

Best regards,

**Comment by Shahrooz11** [comment]
Hi,

Thanks. I have tried the code in the terminal, But faced with this error. How to fix, please. Highly appreciated. 

Regards,
Shahrooz

<img width="1435" alt="Screen Shot 2019-07-25 at 7 42 24 pm" src="https://user-images.githubusercontent.com/48337422/61864419-bc9b1e80-af14-11e9-8b9c-bbfa83fa2400.png">

**Comment by vlkong** [comment]
It cames out that the docloud package for python 3.7 was missing.
I just redeployed it.

Can you please try to install docplex once again ?

Thanks

**Comment by Shahrooz11** [comment]
Hi,

Yes. The problem has now been solved. Thank you very much
Regards,
