### ISSUE TITLE
example failed at library import: chicago_coffee_shops (jupyter/chicago_coffee_shops.ipynb)

### ISSUE THREAD

**Issue by smarterway** [IBMDecisionOptimization/docplex-examples#2]
In running (cell): 
# Simple distance computation between 2 locations.
from geopy.distance import great_circle

Receiving error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-b04e584181a8> in <module>()
      1 # Simple distance computation between 2 locations.
----> 2 from geopy.distance import great_circle
      3 
      4 def get_distance(p1, p2):
      5     return great_circle((p1.y, p1.x), (p2.y, p2.x)).miles

ModuleNotFoundError: No module named 'geopy'

Please help.

Thanks.

**Comment by vlkong** [comment]
Closing the issue, since there's no news or nothing new on this.
