### ISSUE TITLE
Python Setup.py install 

### ISSUE THREAD

**Issue by TimZhu-23** [IBMDecisionOptimization/docplex-examples#20]
When solving an optimization problem in python using docplex(not docplex cloud) I got this error :  **** Promotional version. Problem size limits exceeded, CPLEX code=1016
Knowing that I have an academic version of Cplex on my macbook, and I installed docplex using pip install docplex only. When looking for a solution I found that I should install the package using setup.py. When trying to do so I got the error : "python: can't open file 'setup.py': [Errno 2] No such file or directory." I ve checked that the file does exist in the Cplexdirectory. But I don’t know what Should I write in the terminal so the file will be opened from the directory (Cplexhome/cplex/python/version/platform)

Is there anyone who can be of any help?
Thank you in advance

**Comment by TimZhu-23** [comment]
It solved the issue related to installing the API using setup.py. I used the command cd/ directory. But I still getting the same error regarding the limit size. Any help please ? Thank you

**Comment by vlkong** [comment]
Hi,

Can you please check that the python interpreter you use when you run your program is the same than the one on which you ran "python setup.py install" ?

**Comment by TimZhu-23** [comment]
Thank you for your response.
I have solve the problem. I used cd command to change the working directory and Setup.py to install the package. 
Best,

**Comment by vlkong** [comment]
Ok thanks !
Best regards,
