### ISSUE TITLE
Schedule machine and tools with setup times

### ISSUE THREAD

**Issue by maxcast29** [IBMDecisionOptimization/docplex-examples#21]
Hi everyone,

I'm pretty new to CPLEX and CP Optimizer, I have done a first "simple" scheduling project and I can see the great potential of this technology for complex scheduling project.

I am currently working on a new problem  and I'm having a hard time getting started with.

Here's the detail: I need to schedule N jobs on M machines. Each job contains only one operation. So far nothing complicated. However each product to create needs a specific tool t that can't be installed on any machine (I have a table telling me which tool can go on which machine).

Moreover, installing a tool on a machine requires a setup time of 4h, and as the products created can be of different colors, there is another setup time for the color (for example, I have to create a product that requires the tool t and that must be white, so I have 4h for the tool setup + 2h for the color setup). If for a next job, I use the same machine with the same tool and the same color, I don't have any setup to do, if I have to change the color then I have a 2h setup, and if I have to change the tool I have another 4h setup etc... Obviously, a tool and a machine can't be used twice at the same time.

The objective is to minimize the delay time of my jobs (I have a delivery date for each job).

I searched in the different examples available on this repo (I work with the python API of docplex ) but I didn't find a similar problem. Have you ever seen such a problem, and if so could you recommend a resource that could help me get started?

Thank you for your help.

Maxime

**Comment by vlkong** [comment]
Hello.

Issues in this repository are only used for support issues about docplex examples themself.
For a more general modeling question like yours, you will have more response from stackoverflow (https://stackoverflow.com/questions/tagged/cplex or https://stackoverflow.com/questions/tagged/docplex).

If you tag your question with `cplex` + `docplex`, your question will get the attention of OR specialists. Note also that we have a library of models in OPL that is much larger than for
docplex, so maybe someone will point you to one.

Thanks.

**Comment by maxcast29** [comment]
Thanks for the answer,

will do right now.
