### ISSUE TITLE
AttributeError: 'Environment' object has no attribute '_apienc'

### ISSUE THREAD

**Issue by gstecca** [IBMDecisionOptimization/docplex-examples#22]
I am trying to run the Pasta Production problem.
When running the cell:
```
# --- constraints ---
# demand satisfaction
mdl.add_constraints((inside_vars[prod] + outside_vars[prod] >= prod[1], 'ct_demand_%s' % prod[0]) for prod in products)

# --- resource capacity ---
mdl.add_constraints((mdl.sum(inside_vars[p] * consumptions[p[0], res[0]] for p in products) <= res[1], 'ct_res_%s' % res[0]) for res in resources)

mdl.print_information()
```

I got the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-ebe7857b77ab> in <module>
      1 # --- constraints ---
      2 # demand satisfaction
----> 3 mdl.add_constraints((inside_vars[prod] + outside_vars[prod] >= prod[1], 'ct_demand_%s' % prod[0]) for prod in products)
      4 
      5 # --- resource capacity ---

~/anaconda3/lib/python3.6/site-packages/docplex/mp/model.py in add_constraints(self, cts, names)
   3387             return self._lfactory._new_constraint_block2(cts, names)
   3388         else:
-> 3389             return self._lfactory._new_constraint_block1(cts)
   3390 
   3391 

~/anaconda3/lib/python3.6/site-packages/docplex/mp/mfactory.py in _new_constraint_block1(self, cts)
    880                 if filterfn(ct, ctname=None, check_for_trivial_ct=check_trivial, arg_checker=checker):
    881                     posted_cts.append(ct)
--> 882         self._post_constraint_block(posted_cts)
    883         return posted_cts
    884 

~/anaconda3/lib/python3.6/site-packages/docplex/mp/mfactory.py in _post_constraint_block(self, posted_cts)
    885     def _post_constraint_block(self, posted_cts):
    886         if posted_cts:
--> 887             ct_indices = self._engine.create_block_linear_constraints(posted_cts)
    888             self._model._register_block_cts(self._model._linct_scope, posted_cts, ct_indices)
    889 

~/anaconda3/lib/python3.6/site-packages/docplex/mp/cplex_engine.py in create_block_linear_constraints(self, linct_seq)
    792 
    793         range_values = [ct.cplex_range_value() for ct in linct_seq] if has_ranges else None
--> 794         ret_add = fast_add_linear(self._cplex, cpx_linexprs, cpx_sense_string, cpx_rhss, cpx_names, ranges=range_values)
    795         return self._allocate_range_index(size=block_size, ret_value=ret_add, scope=self._lincts_scope)
    796 

~/anaconda3/lib/python3.6/site-packages/docplex/mp/cplex_engine.py in fast_add_linear(cpx, lin_expr, cpx_senses, rhs, names, ranges)
    129         cpxenv = cpx._env
    130         with chbmatrix(lin_expr, cpx._env_lp_ptr, 0,
--> 131                        cpxenv._apienc) as (rmat, nnz):
    132             addrows(cpxenv._e, cpx._lp, 0,
    133                     len(rhs), nnz, rhs, cpx_senses,

AttributeError: 'Environment' object has no attribute '_apienc'_

my environment info are:
* system is: Linux 64bit
* Python version 3.6.9, located at: /home/gstecca/anaconda3/bin/python
* docplex is present, version is (2, 10, 155)
* CPLEX library is present, version is 12.10.0.0, located at: /home/gstecca/anaconda3/lib/python3.6/site-packages
* pandas is present, version is 0.25.2

**Comment by vlkong** [comment]
Hi,

Please update docplex to 2.12.xxx, 2.10 does not support cplex 12.10.

Thanks

**Comment by gstecca** [comment]
Thanks for the hint! In the update process i got some conflicts. I reinstalled the anaconda distribution with python 3.7. I then installed IBM optimization studio v 12.10 (academic license) and python support. Now everything is perfect. 
I will do further tests with docplex and cplex free edition for my students.

**Comment by vlkong** [comment]
Thanks for your interest. Have a nice day.
