### ISSUE TITLE
CPLEX runtime not found: please install CPLEX or solve this model on DOcplexcloud

### ISSUE THREAD

**Issue by Cagrali** [IBMDecisionOptimization/docplex-examples#24]
Hello,

I am new to Python-Cplex modeling. Normally, I use Java. 

I was just trying to learn some about it. Let me explain what I did and tried:

- I use PyCharm (I don't know if it matters), I opened the project with Python 3.7
- I just copied and pasted your code and I got this: 
Traceback (most recent call last):
  File "C:/Users/cansu/PycharmProjects/Diet2/Diet2.py", line 109, in <module>
    s = mdl.solve()
docplex.mp.utils.DOcplexException: CPLEX runtime not found: please install CPLEX or solve this model on DOcplexcloud
![image](https://user-images.githubusercontent.com/16446745/84078260-9e140980-a9a6-11ea-9dd9-39911f0dbe6f.png)
- I tried several methods to solve. Some were saying it is because of PYTHONPATH which I don't know what it is. (I created a variable as PYTHONPATH in Control Panel > System Properties : C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cplex\python\3.7\x64_win64)
-I tried with different Python versions.

So far, nothing worked. I really really appreciate it if you could help me? Please remember that, I am new to Python and I don't know many things about Python-Cplex modeling including DOcplexcloud.

Regards,

**Comment by vlkong** [comment]
Hi,

There are a few things you can do to solve:
- The first thing, following the [Python setup](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/set_up/Python_setup.html) section in the CPLEX user manual, is to make sure you have a console with your python envrionment, then 
```
C:> cd C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cplex\python\3.7\x64_win64
C:> python setup.py install
```

- If you prefer the environment varaible method, you can set the PYTHONPATH in control panel,
but as far as I know, you need to restart PyCharm (you can check that by printing the value of `sys.path`)

**Comment by Cagrali** [comment]
Thank you! When I reopened PyCharm, it worked!
