### ISSUE TITLE
CPLEX runtime Error

### ISSUE THREAD

**Issue by amirvaez** [IBMDecisionOptimization/docplex-examples#30]
I have install CPLEX 12.10.0.0 on my Windows. I have been using DOcplex for a while and it was OK. After some software update, I am getting the following error.
DOcplexException: CPLEX runtime not found: please install CPLEX or solve this model on DOcplexcloud

I installed the CPLEX 12.10.0.0 again and downgraded my python to 3.7 and use the following command in anaconda prompt:

C:> cd "C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cplex\python\3.7\x64_win64" 
C:> python setup.py install

and I am receiving the following error. 

Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    main()
  File "setup.py", line 53, in main
    raise Exception(VERSION_ERROR)
Exception: CPLEX 12.10.0.0 is not compatible with this version of Python.

It is weird since I only have python 3.7 on my Windows and I am pretty sure that python 3.7 is compatible with CPLEX 12.10.0.0.  When I change directory to C:> cd "C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cplex\python\3.7\x64_win64" , there is no error.

I really appreciate if you could help me to resolve this error. ( I am new to python and I would appreciate if you let me know all of the steps.)

Thank you in advance,

**Comment by vlkong** [comment]
Hello,

Can you please print the result of

```
python -c "import sys; print(sys.executable); print(sys.version_info)"
```

**Comment by amirvaez** [comment]
Hi,


Thank you for your response. Here is the result:


sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)



Best,


Amirhossein Vaeztehrani,  Ph.D. candidate,

Department of Management Sciences,

University of Waterloo

________________________________

**Comment by amirvaez** [comment]
Hello again,


Do you have any idea why this did happen to my CPLEX access? Please let me know if you find any potential solution to solve this issue.


Thank in advance,


Amirhossein Vaeztehrani,  Ph.D. candidate,

Department of Management Sciences,

University of Waterloo

________________________________

**Comment by vlkong** [comment]
So you say you want to install CPLEX in your python 3.7, but you are running a python 3.8.

You can do one of two things:
1 - check that you are actually running the right python executable for 3.7 and proceed with what you did in your original post
2 - install the python 3.8 wrappers if python 3.8 is right for you.

Thanks

**Comment by amirvaez** [comment]
Yes,


Actually, my Jupyter notebook had been updated to a version using Python 3.8 and COLEX was using 3.7. When I downgraded Jupyter notebook to Python 3.7, my problem is resolved.


Amirhossein Vaeztehrani,  Ph.D. candidate,

Department of Management Sciences,

University of Waterloo

________________________________
