### ISSUE TITLE
pwl question

### ISSUE THREAD

**Issue by Pein-hub** [IBMDecisionOptimization/docplex-examples#31]
Is there a jupyter example about PWL（Piecewise linear functions）？ 
I can't find it。

**Comment by vlkong** [comment]
Hi,

There is a section on approximating a non-linear program with piecewise linear functions in the [Beyond Linear Programming](https://github.com/IBMDecisionOptimization/docplex-examples/blob/master/examples/mp/jupyter/tutorials/Beyond_Linear_Programming.ipynb) tutorial.

Or you can just create a notebook and import https://github.com/IBMDecisionOptimization/docplex-examples/blob/master/examples/mp/modeling/sailcopw.py

Best regards,

**Comment by Pein-hub** [comment]
Thank u!
