### ISSUE TITLE
Calculating ceiling of an expression

### ISSUE THREAD

**Issue by ckuehl** [IBMDecisionOptimization/docplex-examples#32]
What is the proper way to calculate the ceiling of an expression when using CP Optimizer via docplex?

The C# ILOG.CP library has a `Ceil` method that writes out to the model export file as `_ceil`. I see references to `_ceil` in `docplex/cp/catalog.py` but cannot figure out how to use it in my code.

Thanks!

**Comment by ooudot** [comment]
The ceil() function is NOT supported officially in docplex.cp, even if the operation descriptor may have been present at a time, but in internal code that was partly generated.
Anyway, it is probable that we will make it available in the next future.

**Comment by ckuehl** [comment]
I appreciate the response. I was able to work around the limitation by implementing an integer variable and some constraints to achieve the same desired outcome, but would appreciate ceil being added in a future release so that I can re-simplify my code.

(I also slightly modified docplex to support ceil, but won't share that here for now in favor of your officially supported version of the functionality.)

**Comment by ooudot** [comment]
I know what you have put between parenthesis :-) 
Thanks to not share it as it may have unexpected side effects in the future.
