### ISSUE TITLE
how to remove cplex error 1232

### ISSUE THREAD

**Issue by vaibhavi9296** [IBMDecisionOptimization/docplex-examples#33]
i am writting code having SOCP constraint in GAMS using cplex ,all equations are correct still the code is not working showing infeasible result and error 1232 pls help

**Comment by vlkong** [comment]
Hello,

I will need some code to reproduce your issues. Can you please share it here ?

**Comment by vaibhavi9296** [comment]
Thank you for your response
Actually error got resolved now
