### ISSUE TITLE
Error in Docplex documentation

### ISSUE THREAD

**Issue by jkinable** [IBMDecisionOptimization/docplex-examples#4]
Method: docplex.cp.modeler.no_overlap(sequence, distance_matrix=None, is_direct=None)
http://ibmdecisionoptimization.github.io/docplex-doc/cp/docplex.cp.modeler.py.html#docplex.cp.modeler.no_overlap

The documentation seems to suggest that parameter is_direct is a boolean (True or False), but providing a boolean throws an exception. instead a value 0 or 1 is expected.

Finally it would be very helpful to include some more examples, including the java/c++ examples. Currently there is no python example where sequencing with setup times is used.

**Comment by ooudot** [comment]
Thanks a lot for this comment Joris. We will fix the problem and try to add more examples.
