### ISSUE TITLE
examples/mp/jupyter/tutorials/Linear_Programming.ipynb error！

### ISSUE THREAD

**Issue by chenjw505** [IBMDecisionOptimization/docplex-examples#44]
In the 【3.5.7.2 Infeasible models in DOcplex】
First：
I think the `add a new (infeasible) constraint` should be `cell`  instead of `desk`;
because the constraint `0.5desk + 0.4cell  <= 490`, if desk >= 1100, the constraint  will be never satisfied.  But the tutorials is just update the constraint  `0.2desk + 0.4 cell <=  400` to `0.2desk + 0.4 cell <=  400 + overtime`, so the model wil be infesiable.

Second:
the code to add new constraint :
```
# create a new model, copy of m
im = m.copy()
# get the 'desk' variable of the new model from its name
idesk = im.get_var_by_name('desk')
# add a new (infeasible) constraint
im.add_constraint(idesk >= 1100);
# solve the new proble, we expect a result of None as the model is now infeasible
ims = im.solve()
if ims is None:
    print('- model is infeasible')
```

the new constraint is add to new model 【im】, but next code for soft constraint is 【m】, this will be error to solve the problem.

```
overtime = m.continuous_var(name='overtime', ub=40)
ct_assembly.rhs = 400 + overtime
m.maximize(12*desk + 20 * cell - 2 * overtime)
```

I print the `m.get_constraint_by_index(4)` and `im.get_constraint_by_index(4)`, just model【im】 has the new constraint (desk > 1100).  So the next code to solve model 【m】is pointless to the soft  constraint。

In general， the tutorials jupyter for 【3.5.8  Correcting infeasible models】 is not quite right。
1， the new constraint for decision variable should be 【cell】
2，the soft constraint for model should be 【im】 

If you need， I wanna provide a PR to fix this 。

**Comment by vlkong** [comment]
Hi,

Team will have a look - sorry, for intellectual property reasons, we cannot accept PR in docplex.
Thanks for the report
