### ISSUE TITLE
Error in using set_starting_point()

### ISSUE THREAD

**Issue by oriontang** [IBMDecisionOptimization/docplex-examples#5]
Hi there seems to be an error in setting starting solution for cp optimizer. I first obtain a solution the the restricted version of my original problem. I query the solutionResult and store it in msol. Then I generate CpoModelSolution variable by calling msol.get_solution(). But when I try to set starting point using this solution variable by calling mdl.set_solution(msol.get_solution()) (suppose my model is mdl), I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-de97620d4ab9> in <module>()
      1 fullcp = gen_pure_cp(tM, dM)
      2 fullcp.set_starting_point(msol.get_solution())
----> 3 msol_pure_cp = fullcp.solve(TimeLimit = 300, LogVerbosity = 'Verbose')
      4 with open('../log/full-cp40.txt', 'a') as pure_cp_log:
      5     pure_cp_log.write(msol_pure_cp.get_solver_log())

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/model.py in solve(self, **kwargs)
    890             :class:`~docplex.cp.utils.CpoException`: (or derived) if error.
    891         """
--> 892         solver = self._create_solver(**kwargs)
    893         msol = solver.solve()
    894         solver.end()

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/model.py in _create_solver(self, **kwargs)
   1306             New solver properly initialized.
   1307         """
-> 1308         solver = CpoSolver(self, **kwargs)
   1309         for l in self.listeners:
   1310             solver.add_listener(l)

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solver/solver.py in __init__(self, model, **kwargs)
    429 
    430         # Determine appropriate solver agent
--> 431         self.agent = self._get_solver_agent()
    432 
    433         # Add solver listener for environment

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solver/solver.py in _get_solver_agent(self)
    886         if is_string(alist):
    887             aname = alist
--> 888             agent = self._create_solver_agent(alist)
    889         else:
    890             # Search first available agent in the list

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solver/solver.py in _create_solver_agent(self, aname)
    952 
    953         # Create agent instance
--> 954         agent = sclass(self, sctx.params, sctx)
    955         return agent
    956 

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solver/solver_local.py in __init__(self, solver, params, context)
    127 
    128         # Convert model into CPO format
--> 129         cpostr = self._get_cpo_model_string()
    130 
    131         # Encode model

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solver/solver.py in _get_cpo_model_string(self)
    253         stime = time.time()
    254         cplr = CpoCompiler(self.model, params=self.params, context=self.context.get_root())
--> 255         cpostr = cplr.get_as_string()
    256         self.expr_map = cplr.get_expr_map()
    257         self.process_infos[CpoProcessInfos.MODEL_COMPILE_TIME] = time.time() - stime

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/cpo_compiler.py in get_as_string(self)
    172         # Print the model into a string
    173         out = StringIO()
--> 174         self.write(out)
    175         res = out.getvalue()
    176         out.close()

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/cpo_compiler.py in write(self, out)
    272             out.write(u"startingPoint {\n")
    273             for var in spoint.get_all_var_solutions():
--> 274                 self._write_starting_point(out, var)
    275             out.write(u"}\n")
    276 

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/cpo_compiler.py in _write_starting_point(self, out, var)
    353             self._compile_interval_var_starting_point(var, cout)
    354         else:
--> 355             raise CpoException("Internal error: unsupported starting point variable: " + str(var))
    356         # Write variable starting point
    357         out.write(self._get_expr_id(var) + u" = " + u''.join(cout) + u";\n")

~/anaconda3/envs/opt/lib/python3.6/site-packages/docplex/cp/solution.py in __str__(self)
    452     def __str__(self):
    453         """ Convert this expression into a string """
--> 454         return self.get_name() + ": (" + ", ".join([v.get_name() for v in self.lvars]) + ")"
    455 
    456 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by ooudot** [comment]
Hi oriontang,

In fact, only integer_var(s) and interval_var(s) are allowed in a starting point. To bypass the problem, I recommand that you create a new CpoModelSolution just with this elements.

For the future, I will enhance documentation to precise this.
Moreover, because you are using a solution that may contain other elements, I will change the code to just ignore what is not integer_var(s) and interval_vars().

Thanks a lot to have informed us about this problem.

**Comment by oriontang** [comment]
Hi ooudot, thanks for the reply. To create a new CpoModelSolution variable with those elements, do I do the following: (say I have a CpoSolveResult var called msol and starting point var called start)

```
for sol in msol.get_all_var_solutions():
    if isinstance(sol, CpoIntVarSolution) or isinstance(sol, CpoInervalVarSolution):
        start.add_var_solution(sol)
```

Thanks!

**Comment by ooudot** [comment]
Yes, sounds good, except typo in CpoInervalVarSolution :-)

**Comment by oriontang** [comment]
Thanks a lot ooudot. Another thing I is when I tried to modify the source code under docplex/cp, it seems my change is not taking effect? For example if I comment out certain parts of conditional statement, the code still produces the same error as before. Do I need to recompile things to make python API change accordingly?

Thanks again.

**Comment by ooudot** [comment]
What do you mean by "modify the source code under docplex/cp" ?
Otherwise, normally Python is recompiling automatically when source has been changed.

**Comment by vlkong** [comment]
Closing this issue since there is no changes for more than 6 months. Feel free to open a new issue if needed.
