### ISSUE TITLE
how to output multi results

### ISSUE THREAD

**Issue by weidongzhou1994** [IBMDecisionOptimization/docplex-examples#54]
as title, I want to choose the best result from multi results, but docplex only output a result, how to output multi results.

**Comment by vberaudi** [comment]
If you want to collect all the solutions, you should look at callbacks.
Here is an example which shows how those callbacks work in docplex: https://github.com/PhilippeCouronne/docplex_contribs/blob/master/docplex_contribs/src/cut_callback.py
and the doc: http://ibmdecisionoptimization.github.io/docplex-doc/mp/docplex.mp.callbacks.cb_mixin.html#docplex.mp.callbacks.cb_mixin.ModelCallbackMixin
