### ISSUE TITLE
how can i find convertAllIntVars

### ISSUE THREAD

**Issue by GeniusTian** [IBMDecisionOptimization/docplex-examples#55]
i want solve custstock Full integer problem using column generation by python ,but i could find nothing in doc
![image](https://user-images.githubusercontent.com/52662076/129565924-ea38ba26-f2af-495c-a402-c8eaf63dea62.png)

**Comment by PhilippeCouronne** [comment]
Unfortunately, Docplex provides no column-oriented API formodeling.
The cutstock example in this github relies on dual values, so changing all variables won't work either.
I suggest you consider the Cplex/_python matrix-based API, doc is here:

https://www.ibm.com/docs/en/icos/20.1.0?topic=SSSA5P_20.1.0/ilog.odms.cplex.help/refpythoncplex/html/frames.html

**Comment by GeniusTian** [comment]
thank you for your answer
