### ISSUE TITLE
What does 'integral solution' in the objective column mean (CPLEX PYTHON API SOLUTION? 

### ISSUE THREAD

**Issue by HengChheang** [IBMDecisionOptimization/docplex-examples#59]
https://www.ibm.com/docs/en/icos/12.8.0.0?topic=mip-progress-reports-interpreting-node-log&fbclid=IwAR1O7zuD1d0Q8YCuE-LLFEi1-CWbeaxe201but23qMQhnVQvXTEhkg3DZTo
I read the information in the link above to learn more about the Progress reports: interpreting the node log. However, there is an 'integral' word present in the 'objective' column, and I'm not sure how to interpret it and why it is there. Could any provide the answer? All answers would be appreciated!
@vlkong

**Comment by vlkong** [comment]
Hi,

My understanding is that the `cplex` log will report `integral` when it founds an integral solution for the MIP, and that the objective for this solution is found in the `best integer` column.

In docplex, there is no such report as you can check the integrality of objective by code.

Note: Questions specifc to CPLEX are best asked on the support forum: https://www.ibm.com/mysupport/s/forumsproduct?language=en_US&name=ILOG%20CPLEX%20Optimization%20Studio&id=0TO50000000226IGAQ

Best regards,

**Comment by HengChheang** [comment]
Dear vlkong,
Thank you so much for your supports!
