### ISSUE TITLE
cplex limits exceeded problem

### ISSUE THREAD

**Issue by sandy-shirt** [IBMDecisionOptimization/docplex-examples#6]
when i use docplex to solve the model i write , it report the error of cplex limits exceeded problem, however I have installed the cplex acadamic version and when  I try to solve the same model in cplex Optimization Studio , there is no such error , is something I forget to config or somehow ???

the error message is as follow :

CplexSolverError                          Traceback (most recent call last)
C:\Program Files\Python36\lib\site-packages\docplex\mp\cplex_engine.py in solve(self, mdl, parameters, lex_mipstart)
   1455             cpx_probtype = cpx.problem_type[cpx.get_problem_type()]
-> 1456             cpx.solve()  # returns nothing in Python
   1457             cpx_status = cpx.solution.get_status()

C:\Program Files\Python36\lib\site-packages\cplex\__init__.py in solve(self)
   1098             else:
-> 1099                 _proc.mipopt(self._env._e, self._lp)
   1100         elif self.quadratic_constraints.get_num() > 0:

C:\Program Files\Python36\lib\site-packages\cplex\_internal\_procedural.py in mipopt(env, lp)
    628         status = CR.CPXXmipopt(env, lp)
--> 629     check_status(env, status)
    630 

C:\Program Files\Python36\lib\site-packages\cplex\_internal\_procedural.py in __call__(self, env, status, from_cb)
    302                     error_string = geterrorstring(env, status)
--> 303             raise CplexSolverError(error_string, env, status)
    304 

CplexSolverError: CPLEX Error  1016: Promotional version. Problem size limits exceeded.

During handling of the above exception, another exception occurred:

DOcplexLimitsExceeded                     Traceback (most recent call last)
<ipython-input-26-b982791520be> in <module>()
----> 1 m.solve(agent='local',url=url, key=key)
      2 m.print_solution()

C:\Program Files\Python36\lib\site-packages\docplex\mp\model.py in solve(self, **kwargs)
   3442                 # if CPLEX is installed go for it
   3443                 force_clean_before_solve = kwargs.get('clean_before_solve')
-> 3444                 return self._solve_local(context, force_clean_before_solve)
   3445             elif have_credentials:
   3446                 # no context passed as argument, no Cplex installed, try model's own context

C:\Program Files\Python36\lib\site-packages\docplex\mp\model.py in _solve_local(self, context, force_clean_before_solve)
   3571         except DOcplexException as docpx_e:  # pragma: no cover
   3572             self._set_solution(None)
-> 3573             raise docpx_e
   3574 
   3575         except Exception as e:

C:\Program Files\Python36\lib\site-packages\docplex\mp\model.py in _solve_local(self, context, force_clean_before_solve)
   3558             self._apply_parameters_to_engine(used_parameters)
   3559 
-> 3560             new_solution = self_engine.solve(self, parameters=parameters)
   3561             has_solution = new_solution is not None
   3562             self._set_solution(new_solution)

C:\Program Files\Python36\lib\site-packages\docplex\mp\cplex_engine.py in solve(self, mdl, parameters, lex_mipstart)
   1482                 cpx_status = 1016
   1483                 cpx_status_string = "Promotional version. Problem size limits exceeded., CPLEX code=1016."
-> 1484                 self._model.fatal_ce_limits()
   1485             else:
   1486                 cpx_status, cpx_status_string = self._parse_cplex_exception_as_status(cpx_se)

C:\Program Files\Python36\lib\site-packages\docplex\mp\model.py in fatal_ce_limits(self, *args)
    776 
    777     def fatal_ce_limits(self, *args):
--> 778         self._error_handler.fatal_limits_exceeded()
    779 
    780     def error(self, msg, *args):

C:\Program Files\Python36\lib\site-packages\docplex\mp\error_handler.py in fatal_limits_exceeded(self)
    212     def fatal_limits_exceeded(self):
    213         docplex_error_stop_here()
--> 214         raise DOcplexLimitsExceeded()
    215 
    216 

DOcplexLimitsExceeded: **** Promotional version. Problem size limits exceeded, CPLEX code=1016

**Comment by vlkong** [comment]
From the error backtrace, it looks like the cplex you have in Python36\lib\site-packages is a Community Edition.
Can you please uninstall this CE version with ```pip uninstall cplex```, then try again with <Your CPLEX_Studio_Academic install path>/cplex/python/3.6/x64_win64 in your PYTHONPATH ?

**Comment by minicap** [comment]
> Hi,
> 
> The error backtrace shows that the cplex you have in Python36\lib\site-packages is a Community Edition.
> 
> Can you please uninstall this CE version with `pip uninstall cplex`, then try again with `<Your CPLEX_Studio_Academic install path>/cplex/python/3.6/x64_win64` in your PYTHONPATH ?

I tried and it didn't work

**Comment by vlkong** [comment]
can you please print your PYTHONPATH (or print(sys.path)) and also print where your cplex is actually imported from using:
```
import cplex
print(cplex.__file__)
```

**Comment by Rakshith-Manandi** [comment]
I've the same problem but I'm on a Mac. I tried installing the community edition using pip install cplex. But also registered with IBM using my student email id and downloaded the app. But I could only download it as the desktop version. I'm trying to run it from command line

**Comment by yaowei717** [comment]
You can download cplex using Anaconda，which can download the matching version.

在2019-05-31 12:03:58，姚伟220172089@seu.edu.cn写道：

I've the same problem but I'm on a Mac. I tried installing the community edition using pip install cplex. But also registered with IBM using my student email id and downloaded the app. But I could only download it as the desktop version. I'm trying to run it from command line

**Comment by vlkong** [comment]
@Rakshith-Manandi I created a new Issue to track your problem https://github.com/IBMDecisionOptimization/docplex-examples/issues/10

**Comment by vlkong** [comment]
Closing this issue since there is no news since my last question 5 month ago.

**Comment by mch9791** [comment]
i have a problem when i tried to install academic cplex with "python setup.py install"
D:\Cplex\cplex\python\3.10\x64_win64>python setup.py install
running install
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-8820.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by vlkong** [comment]
@mch9791 Your errors just look like you don't have the write access to your python installation.
Please make sure you can, or use a virtual environment.
