### ISSUE TITLE
In Firefox, it is not possible to download Cplex

### ISSUE THREAD

**Issue by dmitry-kabanov** [IBMDecisionOptimization/docplex-examples#60]
I try to download Cplex academic version using Firefox, but it is not possible as the webpage https://www-03.ibm.com/isc/esd/dswdown/home.wss?ticket=Xa.2/Xb.Z7LJBh8BR1yMVigVF-6PnLXc/Xc./Xd./Xf./Xg.11498199/Xi./XY.scholars/XZ.iyC1a93VpCdfRcKDv1e3D803HIU_HWi0&partNumber=CJ8GXML requests me to accept cookies using page footer and there is nothing in the page footer. Please see the screenshot of the full page.

When I open the same link in Safari, an overlay appears that allows me to accept cookies, and then, after refreshing the webpage twice, I get to the page with download links.

<img width="1330" alt="Screenshot 2021-11-10 at 16 49 50" src="https://user-images.githubusercontent.com/500073/141145976-cf1a5f2d-d6d4-4fb5-bb3c-cbe0a704f553.png">

**Comment by vlkong** [comment]
Hi,

It just sounds like your Firefox is configured to not allow any cookies.
Can you please try changing your configuration so that cookies are allowed in firefox ?

This page is the Firefox documentation to fix this issue:
https://support.mozilla.org/en-US/kb/websites-say-cookies-are-blocked-unblock-them

Best regards,

**Comment by dmitry-kabanov** [comment]
Cookies work in my Firefox, as I use it as my daily browser.

Firefox has a thing called "tracking protection", which is set to standard level for me (please, see the attached screenshot).

Anyway, when I turn it off completely for https://www-03.ibm.com, it does not help.

<img width="750" alt="Screenshot 2021-11-17 at 11 01 08" src="https://user-images.githubusercontent.com/500073/142180369-292df433-72a0-4eee-8706-5c26eb1a056d.png">

**Comment by vlkong** [comment]
Please open a ticket at https://www.ibm.com/mysupport/s/?language=en_US

(I'm the developper on `docplex`, there is nothing I can do on the websites...)

Thanks
