### ISSUE TITLE
No module named 'setup'

### ISSUE THREAD

**Issue by JefVL** [IBMDecisionOptimization/docplex-examples#63]
I have installed setup.py for cplex API. Yet when I try to import it into my python as mentioned here: https://github.com/IBMDecisionOptimization/docplex-examples/issues/11#issuecomment-503350280 , the code tells me there is no module named 'setup'. Does anybody have any idea how I can fix this?

**Comment by vlkong** [comment]
Hi,

Can you be more specific:
- `I have installed setup.py for cplex API` : what command did you run ?
- `the code tells me there is no module named 'setup'` : can you share the code that's show this error please ?

**Comment by JefVL** [comment]
Yes of course.
I used the command `python setup.py install`.
Then I used `import setup
from docplex.mp.model import Model`, which resulted in the error 'no module named setup'.

**Comment by vlkong** [comment]
There is no `setup` to be imported from `docplex.mp.model` and your syntax is not understood by Python.

The right way to import `Model` is: `from docplex.mp.model import Model`

**Comment by vlkong** [comment]
Note: the code `import setup` that you saw on the other ticket is totally unrelated to normal usage of `docplex`

**Comment by JefVL** [comment]
Okay thank you.
