### ISSUE TITLE
CpoBlackboxFunction could not be imported from docplex.cp.model 

### ISSUE THREAD

**Issue by SHosseini94** [IBMDecisionOptimization/docplex-examples#73]
Hi, I have been using CpoBlackboxFunction on my local laptop since its beta version, and now I have access to its stable version 22.1.0.  Without any problem, this function is working on my local laptop. However, I need to run my code on a high-speed computing cluster, Compute-Canada. Although the installed version on my virtual environment is also 22.1.0 , it gives me an error that **_cannot import name 'CpoBlackboxFunction' from 'docplex.cp.model'_** .

I appreciate you helping me in this regard. 

Best, 
Saeede

**Comment by HuguesJuille** [comment]
Hi,
This is very weird. Could you double-check that you do have the correct version of docplex on this computing cluster (e.g.: `pip freeze | grep docplex` ) ?
Kind regards

**Comment by SHosseini94** [comment]
Hi, 

Yes, you're right. There was a version problem. 

Thanks
